### ISSUE TITLE
Add "Publish a Raster Dataset" section to Exercise 5 Maps

### ISSUE THREAD

**Issue by doublebyte1** [geopython/diving-into-pygeoapi#116]
@krishnaglodha We miss a "Publish a raster dataset" section `[here](https://dive.pygeoapi.io/publishing/ogcapi-maps/),  that shows how to publish raster data using the [MapServer MapScript](https://www.mapserver.org/mapscript) core backend.

More information can be found here: https://docs.pygeoapi.io/en/latest/data-publishing/ogcapi-maps.html#providers

**Comment by krishnaglodha** [comment]
I was able to make setup in pygeoapi to spit data out as MAP format, are you asking me to use mapserver mapscript as client to visualise it ? 
<img width="1496" alt="Screenshot 2023-12-06 at 12 42 23 PM" src="https://github.com/geopython/diving-into-pygeoapi/assets/47075664/6441d954-ec77-41fc-9ab1-c49b8134ace0">

**Comment by krishnaglodha** [comment]
PS : This is the config I have used

```
providers:
            - type: map
              name: MapScript
              data: /data/airport/airport.shp
              options:
                  type: MS_LAYER_POINT
                  layer: airport
                  style: /data/airp.sld
              format:
                  name: png
                  mimetype: image/png
```
