### ISSUE TITLE
Add support for OGC API Features Part 2 - CRS support

### ISSUE THREAD

**Issue by justb4** [geopython/diving-into-pygeoapi#88]
Now that pygeoapi supports [Part 2 - CRS support](http://docs.opengeospatial.org/is/18-058r1/18-058r1.html), it makes sense to upgrade various configs for the WS to showcase. Although defaults (WGS84 with lon,lat axis ordering) apply, it would be good to show support.

Basically for each 'feature' provider the `crs` and `storageCRS` config params need to be added, for example:

```
        providers:
            - type: feature
              name: Elasticsearch
              data: http://elasticsearch_cite:9200/canada-hydat-daily-mean-02hc003
              id_field: IDENTIFIER
              time_field: DATE
# NEW
              crs:
                - http://www.opengis.net/def/crs/OGC/1.3/CRS84
                - http://www.opengis.net/def/crs/EPSG/0/4326
                - http://www.opengis.net/def/crs/EPSG/0/3348
              storage_crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
```

http://www.opengis.net/def/crs/OGC/1.3/CRS84 basically means WGS84 with lon,lat axis ordering, the default.

Also remove all `src_epsg` and `target_epsg` from OGR Providers (they are unsupported and obsolete now). `src_epsg` should be replaced with corresponding `storage_crs`.
See also https://docs.pygeoapi.io/en/latest/crs.html.
